version: "3"
services:
  portainer:
    image: portainer/portainer-ce:lts
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data: