keys:
- &server_bonkyserv age1r54fysts4vszg4jdcm5tdtd4fsduvxsu4u507sdwa5upreu2uejsaq6dxx
- &server_bonkygamer age1tskka6l4fqxfme90hgmqj6g7ffw0np49wzxze7649j7ypukmxs7stp9v4p
- &admin_bianchi age18fmehf33j5pfme8kxkt0gkns6u3jxx9typ3xks49elkuw2q88puqunqflm

creation_rules:
- path_regex: secrets/[^/]+\.yaml$
  key_groups:
  - age:
    - *server_bonkyserv
    - *server_bonkygamer
    - *admin_bianchi
- path_regex: bonkyserv/secrets/[^/]+\.yaml$
  key_groups:
  - age:
    - *server_bonkyserv
    - *server_bonkygamer
    - *admin_bianchi
