version: "3"

services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBxqhn070un/hjcJUmh4P0ZCLyi4rZAF552FzFn60kP5"
