version: "3"

services:
 telegraf:
    image: docker.io/telegraf:1.31
    hostname: bonkymini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var:/hostfs/var:ro
      - /run:/hostfs/run:ro
      #- /etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ../../common/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TELEGRAF_TOKEN}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    ports:
        - 8888:8888