name: Deploy NAS Containers

on:
  push:
    branches:
      - main
    paths:
      - 'nas/**/*'
      - '.github/workflows/nas.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     app: [monitoring, ddns]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TAILSCALE_OAUTH_CLIENT_ID: op://homelab-deploy/tailscale/oauth-client-id
          TAILSCALE_OAUTH_SECRET: op://homelab-deploy/tailscale/oauth-client-secret
          NAS_HOST: op://homelab-deploy/nas/host
          NAS_USER: op://homelab-deploy/nas/user

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ env.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.70.0

      # - name: Install 1Password CLI
      #   uses: 1password/install-cli-action@v1

      - name: deploy over ssh
        # env: 
          # OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # DOCKER_HOST: ssh://${{ env.NAS_USER }}@${{ env.NAS_HOST_IP }}
        run: |
          # cd nas/${{ matrix.app }}
          ssh -o "StrictHostKeyChecking no" ${{ env.NAS_USER }}@${{ env.NAS_HOST }} 'echo $PATH'
          # op run --env-file .env -- docker-compose up -d
